default_platform(:ios)

platform :ios do

  before_all do
    if is_ci
      setup_circle_ci
    end
  end

  desc "Build adhoc and send to Firebase"
  lane :adhoc do
    match(
      type: "adhoc",
      app_identifier: "com.duytq.example.dev",
      readonly: true
    )
    gym(
      scheme: "dev",
      export_method: "ad-hoc",
      output_directory: "output"
    )
    if is_ci
      firebase_app_distribution(
        app: "1:497869998462:ios:b30502bdbfa8f791b34b2f",
        release_notes: "Upload to Firebase",
        groups: "testers"
      )
    end
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "3I935WSDHE",
      issuer_id: "ed1f387a-d513-4de6-947a-46bpo9he3108",
      key_filepath: "fastlane/AuthKey_334DJE5TPX.p8",
    )
    increment_build_number(
      build_number: latest_testflight_build_number(
        initial_build_number: 1,
        version: get_version_number(xcodeproj: "Runner.xcodeproj")
      ) + 1,
    )
    match(
      type: "appstore",
      app_identifier: "com.duytq.example",
      readonly: true
    )
    gym(
      scheme: "prod",
      export_method: "app-store"
    )
    if is_ci
      pilot(
        app_identifier: "com.duytq.example",
        skip_submission: true,
        skip_waiting_for_build_processing: true
      )
    end
  end
  
end
